### ISSUE TITLE
Downstream packages have conflicting dependencies

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/edk#50]
Two ways to fix this

1. [x] Loosen constraints here in the EDK: https://github.com/meltano/edk/pull/47
1. [ ] Remove redundant dependencies in those packages

We should probably do both, but it's easier to start with `1`.

Dependents burndown:

- [x] `dbt-ext`: https://github.com/meltano/dbt-ext/pull/19
- [x] `airflow-ext`: https://github.com/meltano/airflow-ext/pull/32
- [x] `superset-ext`: https://github.com/meltano/superset-ext/pull/8

**Comment by pnadolny13** [comment]
@edgarrmondragon do you have update or estimate of when this can be fixed? It's blocking most of my work and looks like our airflow pipelines will fail tonight if it doesnt get resolved by EOD.

**Comment by edgarrmondragon** [comment]
@pnadolny13 This should've been fixed by #51. Is there a way to reproduce this in squared so I can test?

**Comment by edgarrmondragon** [comment]
- [x] `dbt-ext`: https://github.com/meltano/dbt-ext/pull/19
- [x] `airflow-ext`: https://github.com/meltano/airflow-ext/pull/32
- [ ] `superset-ext`: https://github.com/meltano/superset-ext/pull/8

**Comment by aaronsteers** [comment]
@edgarrmondragon and @pnadolny13 - Can we close this as resolved? Anything outstanding?

**Comment by edgarrmondragon** [comment]
@aaronsteers I just want to confirm that `superset-ext` is working

**Comment by pnadolny13** [comment]
@edgarrmondragon @aaronsteers I just merged https://github.com/meltano/superset-ext/pull/8 after confirming it works, I also had to open https://github.com/meltano/hub/pull/1169 to fix other bugs that were blocking me from testing it.

**Comment by edgarrmondragon** [comment]
I'm gonna close this. We can re-open or log new issues if they come up
